# Workflow para build e deploy de uma aplicação React no GitHub Pages
name: Deploy React to GitHub Pages

on:
  # Executa em pushs para o branch padrão
  push:
    branches: ["master"]

  # Permite a execução manual desse workflow a partir da aba Actions
  workflow_dispatch:

# Define as permissões do GITHUB_TOKEN para permitir o deployment no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação concorrente, ignorando execuções na fila entre a execução em andamento e a mais recente na fila.
# No entanto, NÃO cancele as execuções em andamento, pois queremos permitir que essas implantações de produção sejam concluídas.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Build da aplicação
      run: npm run build

    - name: Upload do artefato
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build

  # Job de deploy
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
